Added support for Ubuntu
nodiscc/distrib-dl pull request #18
Opened 2022-01-03 10:12 UTC by 3isenHeiM

Automatic validation of the GPG key with the ubuntu keyserver.

2022-01-04 18:06 UTC, nodiscc requested changes
`ubuntu` should be added to the `Available distributions:` list L58

Thanks!

2022-01-04 18:06 UTC, nodiscc commented on distrib-dl
> +    # Unofficial image including firmwares
please remove the 4 commented out lines above, there are no alternative images for ubuntu

2022-01-05 09:44 UTC, 3isenHeiM commented
Changes implemented in a new commit.

2022-01-13 17:30 UTC, nodiscc approved these changes
thank you

2022-01-13 17:30 UTC, merged